# refs: https://starship.rs/ja-JP/config/#%E3%83%95%E3%82%9A%E3%83%AD%E3%83%B3%E3%83%95%E3%82%9A%E3%83%88

format = '$all'
right_format = '$time'

[directory]
truncation_length = 6
truncation_symbol = '…/'
style = 'blue bold'

[git_branch]
style ='green bold'

[time]
disabled = false
format = '[$time]($style)'

[git_status]
style = 'yellow'
conflicted = '='
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕'
up_to_date = '✓'
untracked = '?'
stashed = '$'
modified = '!${count}'
renamed = '»'
deleted = '✘'
format = '([\[$all_status$ahead_behind\]]($style))'
